#!/usr/bin/env python3
import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SIGMA_ROOT = REPO_ROOT / "sigma-rules"
NAVIGATOR_DIR = REPO_ROOT / "navigator"
LAYER_FILE = NAVIGATOR_DIR / "coverage_layer.json"

COVERED_COLOR = "#1d9e75"
TAG_RE = re.compile(r"^attack\.t(\d+(?:\.\d+)?)$")


def extract_technique_ids(tags):
    if not tags or not isinstance(tags, list):
        return []
    out = []
    for tag in tags:
        if not isinstance(tag, str):
            continue
        m = TAG_RE.match(tag.strip().lower())
        if m:
            out.append("T" + m.group(1))
    return out


def collect_rules():
    coverage = defaultdict(set)
    rule_count = 0
    if not SIGMA_ROOT.exists():
        return coverage, rule_count
    for path in sorted(SIGMA_ROOT.rglob("*.yml")):
        try:
            with open(path, "r", encoding="utf-8") as fh:
                data = yaml.safe_load(fh)
        except (yaml.YAMLError, OSError) as exc:
            print(
                f"[coverage_mapper] Skipping {path.name}: {exc}",
                file=sys.stderr,
            )
            continue
        if not isinstance(data, dict):
            continue
        techs = extract_technique_ids(data.get("tags") or [])
        if not techs:
            continue
        rule_count += 1
        for tid in techs:
            coverage[tid].add(path.name)
    return coverage, rule_count


def build_layer(coverage):
    techniques = []
    for tid in sorted(coverage):
        techniques.append(
            {
                "techniqueID": tid,
                "color": COVERED_COLOR,
                "comment": ", ".join(sorted(coverage[tid])),
                "enabled": True,
                "showSubtechniques": False,
            }
        )
    return {
        "name": "DetectLab-CI Coverage",
        "versions": {"attack": "14", "navigator": "4.9", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            f"Auto-generated by coverage_mapper.py on {date.today().isoformat()}"
        ),
        "filters": {"platforms": ["Windows"]},
        "sorting": 0,
        "hideDisabled": False,
        "techniques": techniques,
        "legendItems": [{"label": "Covered", "color": COVERED_COLOR}],
        "metadata": [],
        "links": [],
    }


def main():
    coverage, rule_count = collect_rules()
    if rule_count == 0:
        print(
            "[coverage_mapper] No Sigma rules with technique tags found",
            file=sys.stderr,
        )
        return 1

    layer = build_layer(coverage)
    try:
        NAVIGATOR_DIR.mkdir(parents=True, exist_ok=True)
        with open(LAYER_FILE, "w", encoding="utf-8") as fh:
            json.dump(layer, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
    except OSError as exc:
        print(
            f"[coverage_mapper] Failed to write {LAYER_FILE}: {exc}",
            file=sys.stderr,
        )
        return 1

    print(f"[coverage_mapper] Scanned {rule_count} rules")
    print(f"[coverage_mapper] Covered techniques: {len(layer['techniques'])}")
    print(
        f"[coverage_mapper] Layer written to: "
        f"{LAYER_FILE.relative_to(REPO_ROOT).as_posix()}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
